### ISSUE TITLE
could u add v2ray client and chromium web browser

### ISSUE THREAD

**Issue by maichaide** [mdrights/antiG#1]

**Comment by mdrights** [comment]
Hi @maichaide , 
I am not maintaining this project seemingly any more as I am engaging my antiS (LiveSlak) live OS as always. Please take a look at it if you like :)

Thanks anyway for your attention.
Best Wishes
( I may add v2ray back to antiS but may not add chromium web browser since it is too big for a live OS which should be less than 2 GB...)
